name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio

    - name: Run validation tests
      run: |
        python -c "
        import sys
        import asyncio
        
        # Test validation function
        def clean_registration_number(reg_no):
            return reg_no.strip() if len(reg_no.strip()) == 11 and reg_no.strip().isdigit() else ''
        
        # Test cases
        test_cases = [
            ('24012300001', '24012300001'),
            ('invalid', ''),
            ('  24012300002  ', '24012300002'),
            ('123', ''),
            ('2401230000a', ''),
            ('', '')
        ]
        
        for input_val, expected in test_cases:
            result = clean_registration_number(input_val)
            assert result == expected, f'Failed for {input_val}: expected {expected}, got {result}'
        
        print('✅ All validation tests passed!')
        "

    - name: Code quality check
      run: |
        pip install flake8 black
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        black --check .

    - name: Notify Discord - CI Started
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "🔄 CI Pipeline Started"
        description: "Running tests for ${{ github.ref }}"
        color: "0xf39c12"
        username: "GitHub Actions"
        avatar: "https://github.com/github.png"

    - name: Notify Discord - CI Success
      if: success()
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "✅ CI Pipeline Passed"
        description: "All tests passed for ${{ github.ref }}"
        color: "0x2ecc71"
        username: "GitHub Actions"
        avatar: "https://github.com/github.png"

    - name: Notify Discord - CI Failed
      if: failure()
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "❌ CI Pipeline Failed"
        description: "Tests failed for ${{ github.ref }}"
        color: "0xe74c3c"
        username: "GitHub Actions"
        avatar: "https://github.com/github.png"
