name: Monitor Bot Status

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:  # Manual trigger

env:
  VPS_HOST: ${{ secrets.VPS_HOST }}
  VPS_USER: ${{ secrets.VPS_USER }}
  VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "$VPS_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts

    - name: Check Bot Status
      id: status_check
      run: |
        STATUS=$(ssh $VPS_USER@$VPS_HOST "sudo systemctl is-active results-monitor" || echo "failed")
        LOGS=$(ssh $VPS_USER@$VPS_HOST "sudo journalctl -u results-monitor --since '5 minutes ago' | tail -10" || echo "No logs available")
        
        echo "status=$STATUS" >> $GITHUB_OUTPUT
        echo "logs<<EOF" >> $GITHUB_OUTPUT
        echo "$LOGS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Notify Status
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "📊 Bot Status Check"
        description: |
          **Service Status:** `${{ steps.status_check.outputs.status }}`
          
          **Recent Logs:**
          ```
          ${{ steps.status_check.outputs.logs }}
          ```
        color: ${{ steps.status_check.outputs.status == 'active' && '0x2ecc71' || '0xe74c3c' }}
        username: "Bot Monitor"
        avatar: "https://github.com/github.png"

    - name: Restart if Failed
      if: steps.status_check.outputs.status != 'active'
      run: |
        ssh $VPS_USER@$VPS_HOST "sudo systemctl restart results-monitor"
        echo "🔄 Restarted bot service"

    - name: Notify Restart
      if: steps.status_check.outputs.status != 'active'
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "🔄 Bot Restarted"
        description: "Bot service was not running and has been restarted"
        color: "0xf39c12"
        username: "Bot Monitor"
